import * as T from './three.module.js';
const stage=document.querySelector('#stage'),button=document.querySelector('#motion'),preference=matchMedia('(prefers-reduced-motion: reduce)');let paused=preference.matches;
try{
const data=await fetch('/logo/shapes.json').then(r=>r.json());const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;stage.append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,100);camera.position.z=13;const group=new T.Group();scene.add(group);
scene.add(new T.AmbientLight(0xffe1a0,1.6));const light=new T.DirectionalLight(0xffedbd,4.5);light.position.set(-3,4,7);scene.add(light);const rim=new T.DirectionalLight(0xffd080,3);rim.position.set(4,-2,4);scene.add(rim);
const studio=new T.Scene();studio.background=new T.Color('#726549');for(const x of [-5,5]){const card=new T.Mesh(new T.PlaneGeometry(5,12),new T.MeshBasicMaterial({color:0xfff5db}));card.position.set(x,3,8);card.lookAt(0,0,0);studio.add(card)}const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(studio,.03).texture;pm.dispose();
const gold=new T.MeshStandardMaterial({color:0xe5b955,metalness:.84,roughness:.23}),edge=new T.MeshStandardMaterial({color:0xa56b20,metalness:.8,roughness:.3});
function path(points,Type){return new Type(points.map(([x,y])=>new T.Vector2((x-327.5)/100,(447.5-y)/100)))}
for(const s of data){if(Math.max(...s.outer.map(p=>p[0]))>480)continue;const shape=path(s.outer,T.Shape);shape.holes=s.holes.map(p=>path(p,T.Path));group.add(new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:true,bevelThickness:.02,bevelSize:.01,bevelSegments:3,steps:1}),[gold,edge]));}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=Math.max(12,3.2/(Math.tan(16*Math.PI/180)*camera.aspect));camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();
let time=0,last=performance.now(),dirty=true;function label(){button.textContent=paused?'Play ↔':'Pause ↔';button.setAttribute('aria-label',paused?'Play animation':'Pause animation');button.setAttribute('aria-pressed',String(paused))}label();button.onclick=()=>{paused=!paused;dirty=true;label()};preference.onchange=()=>{paused=preference.matches;dirty=true;label()};document.addEventListener('visibilitychange',()=>{last=performance.now();dirty=true});
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden||paused&&!dirty)return;if(!paused)time+=dt;group.rotation.y=Math.sin(time*.32)*.20;group.rotation.x=Math.cos(time*.27)*.025;group.position.y=Math.sin(time*.6)*.08;light.position.x=Math.sin(time*.32)*5;renderer.render(scene,camera);document.querySelector('#fallback').hidden=true;dirty=false;}requestAnimationFrame(frame);
}catch(e){button.hidden=true;console.warn('Static emblem fallback active');}
