(() => {
const $=id=>document.getElementById(id),API='/api/community/';
let user=null,mode='login',thread=null,epoch=0,timer=null,sending=false,pending=null,installPrompt=null;
let history=new Map(),before=0;
const labels={physical:'Physical wellbeing',mental:'Mental wellbeing',other:'A space to talk'};
const states={ai:'AI information assistant',waiting:'Requested team support · replies are not immediate',answered:'Your support team has replied',closed:'Conversation closed · send a message to start again'};
const say=t=>{$('notice').textContent=t||'';};
async function api(path,data){const r=await fetch(API+path,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const j=await r.json();if(!r.ok){if(r.status===401&&user)signout();throw new Error(j.error||'Could not connect. Please try again.');}return j;}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setMode(next){mode=next;$('auth-title').textContent=next==='register'?'Make room for yourself.':next==='recover'?'Recover your account.':'Welcome back.';$('terms').hidden=next!=='register';$('recovery-field').hidden=next!=='recover';$('auth-form').elements.adult.required=next==='register';$('auth-form').elements.recoveryCode.required=next==='recover';$('auth-form').elements.password.autocomplete=next==='login'?'current-password':'new-password';$('login-tab').classList.toggle('active',next==='login');$('register-tab').classList.toggle('active',next==='register');say();}
function signedin(u){user=u;$('welcome').hidden=$('auth').hidden=true;$('workspace').hidden=false;for(const id of ['history-open','logout','delete-account'])$(id).hidden=false;$('greeting').textContent=`How are you, ${u.displayName}?`;newChat();}
function signout(){epoch++;user=thread=null;clearTimeout(timer);history.clear();$('messages').replaceChildren();$('history-list').replaceChildren();$('message').value='';$('workspace').hidden=$('auth').hidden=true;$('welcome').hidden=false;for(const id of ['history-open','logout','delete-account'])$(id).hidden=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function newChat(){epoch++;thread=null;history.clear();before=0;pending=null;clearTimeout(timer);$('chat').hidden=true;$('intake').hidden=false;$('message').value='';say();}
async function openChat(id){epoch++;const e=epoch;thread=id;history.clear();before=0;pending=null;$('intake').hidden=true;$('chat').hidden=false;$('messages').replaceChildren();$('older').hidden=true;await refresh(false,e);schedule();}
function render(){const list=$('messages'),atBottom=list.scrollHeight-list.scrollTop-list.clientHeight<100;list.replaceChildren();for(const m of [...history.values()].sort((a,b)=>a.id-b.id)){const box=document.createElement('div');box.className='bubble '+m.role;const meta=document.createElement('small');meta.textContent=({user:'You',ai:'AI information · not a clinician',team:'Voice of Vrindavan team',notice:'Support notice'})[m.role]+' · '+new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const p=document.createElement('p');p.textContent=m.text;box.append(meta,p);list.append(box);}if(!history.size){const p=document.createElement('p');p.className='fine';p.textContent='You can start with a few words. What has been troubling you, and for how long?';list.append(p);}if(atBottom)list.scrollTop=list.scrollHeight;}
async function refresh(older=false,e=epoch){if(!thread)return;const result=await api(`support/history?id=${encodeURIComponent(thread)}${older?`&before=${before}`:''}`);if(e!==epoch||!user)return;for(const m of result.messages)history.set(m.id,m);before=history.size?Math.min(...history.keys()):0;$('chat-title').textContent=labels[result.thread.category];$('chat-status').textContent=states[result.thread.status];$('human').disabled=result.thread.status==='waiting';if(older||history.size<=100)$('older').hidden=!result.hasMore;render();}
function schedule(){clearTimeout(timer);if(user&&thread)timer=setTimeout(async()=>{try{if(!document.hidden)await refresh();}catch(e){say(e.message);}schedule();},8000);}
$('begin').onclick=()=>{$('welcome').hidden=true;$('auth').hidden=false;setMode('login');};$('login-tab').onclick=()=>setMode('login');$('register-tab').onclick=()=>setMode('register');$('recover').onclick=()=>setMode('recover');
$('auth-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;say();const f=e.currentTarget;try{const result=await api(mode,{username:f.elements.username.value.trim(),password:f.elements.password.value,adult:f.elements.adult.checked,recoveryCode:f.elements.recoveryCode.value.trim()});f.elements.password.value='';if(result.user)signedin(result.user);else setMode('login');if(result.recoveryCode){$('recovery-code').textContent=result.recoveryCode;$('recovery').showModal();}}catch(e){say(e.message);}finally{b.disabled=false;}};
$('recovery-save').onclick=()=>download('voice-of-vrindavan-recovery.txt','Keep this code private.\n'+$('recovery-code').textContent);$('recovery-close').onclick=()=>{$('recovery').close();$('recovery-code').textContent='';};
$('intake-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=new FormData(e.currentTarget);const result=await api('support/new',{category:f.get('category'),language:f.get('language'),consent:f.has('consent')});await openChat(result.id);}catch(e){say(e.message);}finally{b.disabled=false;}};
$('new-chat').onclick=newChat;$('older').onclick=()=>refresh(true).catch(e=>say(e.message));
$('send-form').onsubmit=async e=>{e.preventDefault();if(sending||!thread)return;const text=$('message').value.trim();if(!text)return;const id=thread,v=epoch;if(!pending||pending.text!==text||pending.id!==id)pending={id,text,requestId:crypto.randomUUID()};sending=true;$('send').disabled=true;$('thinking').hidden=false;say();try{await api('support/send',pending);if(v===epoch){pending=null;$('message').value='';await refresh();$('messages').scrollTop=$('messages').scrollHeight;}}catch(e){say(e.message);}finally{sending=false;$('send').disabled=false;$('thinking').hidden=true;}};
$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('send-form').requestSubmit();}};
$('human').onclick=async()=>{if(!thread)return;try{await api('support/human',{id:thread});await refresh();say('Your conversation is in the team inbox. Replies are not immediate. You can keep writing here.');}catch(e){say(e.message);}};
$('history-open').onclick=async()=>{try{const result=await api('support/list');const list=$('history-list');list.replaceChildren();for(const t of result.threads){const b=document.createElement('button');b.className='history-row';b.textContent=labels[t.category];const small=document.createElement('small');small.textContent=new Date(t.updated_at).toLocaleDateString()+' · '+states[t.status];b.append(small);b.onclick=()=>{$('history').close();openChat(t.id).catch(e=>say(e.message));};list.append(b);}if(!result.threads.length)list.textContent='Your conversations will appear here.';$('history').showModal();}catch(e){say(e.message);}};$('history-close').onclick=()=>$('history').close();
$('download').onclick=async()=>{if(!thread)return;try{let cursor=0,all=[],more=true;for(let i=0;i<100&&more;i++){const r=await api(`support/history?id=${thread}${cursor?'&before='+cursor:''}`);all.unshift(...r.messages);more=r.hasMore;cursor=r.messages[0]?.id||0;}if(more)throw new Error('This chat is too large for a single download.');download('voice-of-vrindavan-chat.txt',all.map(m=>`${new Date(m.createdAt).toISOString()} · ${m.role}\n${m.text}`).join('\n\n'));}catch(e){say(e.message);}};
$('delete-chat').onclick=async()=>{if(!thread||!confirm('Permanently delete this support chat?'))return;try{await api('support/delete',{id:thread});newChat();say('Conversation deleted.');}catch(e){say(e.message);}};
$('delete-account').onclick=async()=>{const password=prompt('Enter your password to permanently delete your account and chats.');if(!password)return;try{await api('delete-account',{password});signout();say('Account deleted.');}catch(e){say(e.message);}};
$('logout').onclick=async()=>{try{await api('logout',{});signout();}catch(e){say(e.message);}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true;}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/app/sw.js').catch(()=>{});
api('me').then(r=>{if(r.user)signedin(r.user);}).catch(e=>say(e.message));
})();
