(()=>{const $=id=>document.getElementById(id);let token='',id='',offset=0,before=0,epoch=0,timer,pending=null;const records=new Map();const say=t=>{$('notice').textContent=t||'';};
function lock(){epoch++;token=id='';clearTimeout(timer);$('desk').hidden=$('lock').hidden=true;$('access').hidden=false;$('token').value='';$('reply').value='';$('inbox').replaceChildren();$('messages').replaceChildren();records.clear();}
function touch(){clearTimeout(timer);if(token)timer=setTimeout(lock,15*60000);}document.addEventListener('pointerdown',touch);document.addEventListener('keydown',touch);
async function api(path,data){const r=await fetch('/api/community/admin/support/'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const j=await r.json();if(!r.ok){if(r.status===401)lock();throw new Error(j.error||'Request failed.');}return j;}
async function inbox(){const e=epoch,r=await api('inbox?offset='+offset);if(e!==epoch||!token)return;const list=$('inbox');list.replaceChildren();for(const t of r.threads){const b=document.createElement('button');b.className='history-row';b.textContent=(t.urgent?'Urgent flag · ':'')+t.display_name+' · '+t.category;const small=document.createElement('small');small.textContent=t.status+' · '+t.language+' · '+new Date(t.updated_at).toLocaleString();b.append(small);b.onclick=async()=>{id=t.id;records.clear();before=0;$('title').textContent=t.display_name+' · '+t.language;$('conversation').hidden=false;try{await history();}catch(e){say(e.message);}};list.append(b);}if(!r.threads.length)list.textContent='No team conversations on this page.';$('more').hidden=r.threads.length<100;}
async function history(older=false){const e=epoch,selected=id,r=await api('history?id='+id+(older?'&before='+before:''));if(e!==epoch||id!==selected)return;for(const m of r.messages)records.set(m.id,m);before=records.size?Math.min(...records.keys()):0;const list=$('messages');list.replaceChildren();for(const m of [...records.values()].sort((a,b)=>a.id-b.id)){const box=document.createElement('div');box.className='bubble '+m.role;const meta=document.createElement('small');meta.textContent=m.role+' · '+new Date(m.createdAt).toLocaleString();const p=document.createElement('p');p.textContent=m.text;box.append(meta,p);list.append(box);}if(older||records.size<=100)$('older').hidden=!r.hasMore;if(!older)list.scrollTop=list.scrollHeight;}
$('access').onsubmit=async e=>{e.preventDefault();token=$('token').value.trim();$('token').value='';try{await inbox();$('access').hidden=true;$('desk').hidden=false;$('lock').hidden=false;touch();say();}catch(e){lock();say(e.message);}};$('lock').onclick=lock;
$('refresh').onclick=async()=>{offset=0;try{await inbox();if(id)await history();}catch(e){say(e.message);}};$('more').onclick=async()=>{offset+=100;try{await inbox();}catch(e){say(e.message);}};$('older').onclick=()=>history(true).catch(e=>say(e.message));
$('reply-form').onsubmit=async e=>{e.preventDefault();if(!id)return;const b=e.submitter,text=$('reply').value.trim();if(!pending||pending.id!==id||pending.text!==text)pending={id,text,requestId:crypto.randomUUID()};b.disabled=true;try{await api('reply',pending);pending=null;$('reply').value='';await history();await inbox();say('Reply sent.');}catch(e){say(e.message);}finally{b.disabled=false;}};
$('close-thread').onclick=async()=>{if(!id)return;try{await api('close',{id});$('conversation').hidden=true;id='';await inbox();say('Conversation marked resolved.');}catch(e){say(e.message);}};
window.addEventListener('pagehide',lock);
})();
